<div class="titulo"><h2><?= $this->titulo ?></h2></div>
<hr />
<table width="700" align="center">
	<tr>
		<td><h5>Correo electrónico</h5></td>
		<td><h5>Estado</h5></td>
		<td><h5>Estatus</h5></td>
	</tr>
	<?php foreach($this->usuarios as $usuario): ?>
	<tr>
		<td><a href="<?php echo $this->url(array('action'=>'perfil','id'=>$usuario['id_usuario'])); ?>"><?= $usuario['email_usuario'] ?></a></td>
		<td><?= $usuario['tbl_estado_nombre_estado'] ?></td>
		<?php 	$e = null;
					if( $usuario['estatus_usuario'] == 1)$e='Activo';else $e = 'Inactivo'; ?>
		<td><?= $e ?></td>
	</tr>
	<?php endforeach; ?>
</table>
