<?php 	
		$this->headTitle(' | Comienzo cuestionario');
		$sidebar1 = $this->sidebar1;
		$contenido1 = $this->contenido1;
		?>
<div class="sidebarIndex" style="clear:right;">
	<div class="infoHE">
		<h2><?= $sidebar1['titulo_informacion'] ?></h2>
		<hr />
		<?= $sidebar1['contenido_informacion'] ?>
	</div>
</div>

<div class="informacionTesis">
	<h2><?= $contenido1['titulo_informacion'] ?></h2>
	<hr />
	<?= $contenido1['contenido_informacion'] ?>
</div>

<div class="barraPie"></div>
<div class="iniciarCuestionario">
	<form action="/../cuestionario/comenzar" method="post" name="botonComenzarCuestionario" id="botonComenzarCuestionario">
		<table align="center">
		  <tr valign="baseline">
			<td><input class="botonFormulario" name="botonComenzarCuestionario" type="submit" value="Comenzar" style="width:350px;"/></td>
		  </tr>
		</table>
	</form>
</div>
