<?php echo $this->doctype() ?><html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head><meta charset="windows-1252">
<?
	//Título de la página
	$this->headTitle()->prepend('Huella Ecologica Venezuela');
    echo $this->headTitle(); 
	$perfil = $this->perfil;
	$this->headScript()->appendFile("/js/cuestionario.js"); 
?>
<link rel="shortcut icon" href="/../images/favicon.ico" >
<meta name="author" content="Diego León Socorro">
<meta http-equiv="content-language" content="es">

<meta name="copyright" content="&copy; 2012 Universidad Metropolitana">
<meta name="description" content="Software para el calcular la Huella Ecológica en Venezuela.">
<meta name="robots" content="all">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57511740-7', 'auto');
  ga('send', 'pageview');

</script>

<?php
	//Meta
	echo $this->headMeta();
?>
<link href="/css/styles.css" rel="stylesheet" type="text/css" />
<link href="/css/le-frog/jquery-ui-1.8.20.custom.css" rel="stylesheet" type="text/css" />
<?php
	//CSS Stylesheets
	echo $this->headLink();
?>
<?php
	//Librerias de Jquery
	$this->jQuery()->enable();
	$this->jQuery()->uiEnable();
	echo $this->jQuery();

	//JavaScripts
	echo $this->headScript();
?>
<!-- Hotjar Tracking Code for http://huellaecologica.com.ve/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1928299,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<!--END HotJar -->
</head>
<body>
<div id="envoltorio">
		
		<div id="contenido">
			<div class="tituloSeccion">
				<h1>Cuestionario</h1>
				<p>Bienvenid<?php if($perfil['sexo_usuario'] == 'F') echo "a"; else echo "o"; ?>, <a href="/../usuario/perfil"><?php if($perfil['nombre_usuario']!=null)echo $perfil['nombre_usuario']; else echo $perfil['email_usuario']; ?></a></p>
				<br />
				<a href="/../index/cerrar-sesion"><p>Cerrar sesión</p></a>
			</div>

			<?php echo $this->layout()->content; ?>
			
			
		</div>
		
		<div id="ads">
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- Huella Ecológica AdSense -->
			<ins class="adsbygoogle"
				 style="display:inline-block;width:728px;height:90px"
				 data-ad-client="ca-pub-8587366501552430"
				 data-ad-slot="3542618536"></ins>
			<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
		</div>
		
		
		
	<div id="pie">
		<div class="creditos">
			<p class="centrar"><a href="/../usuario/perfil" style="color:#FFF; font-weight:bold; font-size:12px">Volver a mi perfil</a></p>
			<br />
			<p class="centrar">Trabajo de Grado realizado por <a href="https://linkedin.com/in/leonsdiego" style="color:white; text-decoration: underline;">Diego León Socorro</a> para la Universidad Metropolitana</p>
			<p class="centrar" ><strong>Todos los derechos reservados</strong></p>
		</div>
	</div>
</div>
</body>
</html>