<?php 
	$perfil = $this->perfil;
	$fecha = $this->fecha;
	$huella = $this->huella;
	$idCuestionario = $this->idCuestionario;
	$this->headTitle(' | Perfil');
	$this->headScript()->appendFile("/js/js-datepicker/datepicker.js");
	$this->headLink()->appendStylesheet("/css/css-datepicker/datepicker.css");
?>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Grupo', 'Huella ecológica'],
		  <?php
		$resultadosGrupo = $this->resultadosGrupos;
		 foreach( $this->grupos as $grupo )
		 {
			echo "['". $grupo['nombre_grupo'] ."', ". $resultadosGrupo[$grupo['nombre_grupo']] . "],";
		 }
		?>]);        

        var options = {
          title: 'Tu Huella Ecológica por categorías',
          is3D: true
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>

<div class="tituloSeccion"><h1>Resultados del cuestionario inciado el: <?= $fecha ?></h1>
<p>Bienvenid<?php if($perfil['sexo_usuario'] == 'F') echo "a"; else echo "o"; ?>, <a href="/../usuario/perfil"><?php if($perfil['nombre_usuario']!=null)echo $perfil['nombre_usuario']; else echo $perfil['email_usuario']; ?></a></p>
<br />
<a href="/../index/cerrar-sesion"><p>Cerrar sesión</p></a></div>
	<br />
	<h3>Tu Huella Ecológica es de: <span style="color:#090; font-size:18px;"><?= $huella ?></span> Hectáreas Globales</h3>
	<br />
	<p><a href="/../usuario/consejos/cuestionario/<?php echo $idCuestionario . '" style="color:blue;';?>">¿Cómo disminuir mi Huella Ecológica? | Consejos ecológicos</a></p>
	<p><a href="/../usuario/perfil" style="font-size:14px;">Volver a mi perfil</a></p>
    <div id="chart_div" style="width: 900px; height: 500px;"></div>