<?php
	$sidebar4 = $this->sidebar4;
?>

<div class="tituloSeccion">
    <h1>¡Has cerrado tu sesión exitosamente!</h1>
</div>
<div class="sidebarIndex">
	<div class="infoHE">
		<h2><?= $sidebar4['titulo_informacion'] ?></h2>
		<hr />
		<p><?= $sidebar4['contenido_informacion'] ?></p>
		<a href="/../index/informacion"><p class="verde2 derecha">más información</p></a>
	</div>
</div>
<div class="inicioSesion">
		<div ><a href="/../"><h2 style="text-align:center;">Ir al inicio</h2></a></div>
</div>