<?php
	$this->headScript()->appendFile("/SpryAssets/SpryValidationTextField.js")
					   ->appendFile("/SpryAssets/SpryValidationPassword.js")
					   ->appendFile("/js/borrarForm.js");
					   
	$this->headLink()->appendStylesheet("/SpryAssets/SpryValidationTextField.css")
					 ->appendStylesheet("/SpryAssets/SpryValidationPassword.css");
	
	$sidebar4 = $this->sidebar4;
?>
<div class="tituloSeccion"><h1>Bienvenidos</h1></div>
<div class="sidebarIndex">
	<div class="infoHE">
		<h2><?= $sidebar4['titulo_informacion'] ?></h2>
		<hr />
		<p><?= $sidebar4['contenido_informacion'] ?></p>
		<a href="/../index/informacion"><p class="verde2 derecha">más información</p></a>
	</div>
</div>
<div class="inicioSesion">
<h2>Iniciar sesión</h2>
<hr />

<?php if ($this->mensajes): ?>
		<div class="FlashMessage">
			<p>
				<?= $this->mensajes; ?>
			</p>
		</div>
<?php endif; ?>
<?php if ($this->mensajesError): ?>
		<div class="FlashMessageError">
			<p>
				<?php	foreach ($this->mensajesError as $mensajeError):
							echo $mensajeError;
						endforeach;
				?>
			</p>
		</div>
<?php endif; ?>
	
	<form method="POST" action="/index/login" name="formularioSesion" id="formularioSesion" >
		<table align="center">
			<tr valign="baseline">
				<td nowrap="nowrap" align="right">Correo electrónico</td>
				<td><span id="sprytextfield1">
				<?php /* Recibe el parámetro CORREO desde el formulario de registro */$correo = $this->correo; ?>
				<input class="campotexto" type="text" name="email_usuario" id="email_usuario" onfocus="ClearEmail2();" value="<?php if(isset($correo)) echo $correo; else echo 'correo@ejemplo.com' ?>" size="32" />
				<span class="textfieldRequiredMsg">*</span><span class="textfieldInvalidFormatMsg">Formato inválido.</span></span></td>
			</tr>
			<tr valign="baseline">
				<td nowrap="nowrap" align="right">Contraseña</td>
				<td><span id="sprypassword1">
				<input class="campotexto" type="password" name="pass_usuario" id="pass_usuario" onfocus="ClearEmail2();" size="32" />
				<span class="passwordRequiredMsg">*</span></span></td>
			</tr>
			<tr valign="baseline">
				<td nowrap="nowrap" align="right">&nbsp;</td>
				<td><input class="botonFormulario" name="botonInicioSesion" type="submit" value="Iniciar sesión"/></td>
			</tr>
		</table>
		<input type="hidden" name="redirect" value="<?= $this->redirect ?>" />
	</form>
	<a href="/index/registro" style="color:#060;">Registrarme</a>
	<br />
	<br />
	<a href="/index/registro" style="font-size:10px;">Olvidé mi contraseña</a>   
</div>

<script type="text/javascript">

<!--

var sprypassword1 = new Spry.Widget.ValidationPassword("sprypassword1");

var sprytextfield1 = new Spry.Widget.ValidationTextField("sprytextfield1", "email");

//-->

</script>