<?php $perfil = $this->perfil; 
$cuestionarios = $this->cantidadCuestionarios;?>
<?php if ($this->mensajes): ?>
	<div class="FlashMessage" name="FlashMessage">
		<p>
			<?php	foreach ($this->mensajes as $mensaje):
						echo $mensaje;
					endforeach;
			?>
		</p>
	</div>
<?php endif; ?>
<?php if ($this->mensajesError): ?>
	<div class="FlashMessageError">
		<p>
			<?php	foreach ($this->mensajesError as $mensajeError):
						echo $mensajeError;
					endforeach;
			?>
		</p>
	</div>
<?php endif; ?>
<div class="titulo"><h2>Perfil | <?php echo $perfil['nombre_usuario'] ?></h2></div>
<hr />
<form id="perfilUsuario">
	<table align="center">
		<tr>
			<td class="derecha" >Identificador</td>
			<td><?php echo $perfil['id_usuario'] ?></td>
		</tr>
			<tr>
			<td class="derecha" >Nombre</td>
			<td><?php echo $perfil['nombre_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Correo electr&oacute;nico</td>
			<td><?php echo $perfil['email_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >IP</td>
			<td><?php echo $perfil['ip_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >G&eacute;nero</td>
			<td><?php echo $perfil['sexo_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Nivel de instrucci&oacute;n</td>
			<td><?php echo $perfil['tbl_instruccion_nombre_instruccion'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Profesi&oacute;n</td>
			<td><?php echo $perfil['profesion_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Fecha de nacimiento</td>
			<td><?php echo $perfil['fechaNac_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Fecha de registro</td>
			<td><?php echo $perfil['fechaRegistro_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Estado</td>
			<td><?php echo $perfil['tbl_estado_nombre_estado'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Rol</td>
			<td><?php echo $perfil['rol_usuario'] ?></td>
		</tr>
		<tr>
			<td class="derecha" >Estatus</td>
			<?php 	$e = null;
					if( $perfil['estatus_usuario'] == 1)$e='Activo';else $e = 'Inactivo'; ?>
			<td><?= $e ?></td>
		</tr>
		<tr>
			<td class="derecha" >Cuestionarios</td>
			<td><?= $cuestionarios['cant'] ?></td>
		</tr>
	</table>
</form>
<br />
<br />
<div class="titulo"><h2>Editar rol y estatus de <?= $perfil['nombre_usuario'] ?></h2></div>
<hr />
<form action="/../editor/perfil/id/<?= $perfil['id_usuario'] ?>" method="post" name="formularioEditarPerfil" id="formularioEditarPerfil">
	<table align="center">
		<tr valign="baseline">
			<td nowrap="nowrap" align="right">Rol</td>
			<td>
				<select class="campotexto" name="rol_usuario">
					<option value="encuestado" <?php if($perfil['rol_usuario'] == 'encuestado') echo "selected='selected'" ?> >Encuestado</option>
					<option value="visitante" <?php if($perfil['rol_usuario'] == 'visitante') echo "selected='selected'" ?> >Visitante</option>
					<option value="editor" <?php if($perfil['rol_usuario'] == 'editor') echo "selected='selected'" ?> >Editor</option>
				</select>
			</td>
		</tr>
		<tr valign="baseline">
			<td nowrap="nowrap" align="right">&nbsp;</td>
			<td><input class="botonFormulario" name="botonEditarUsuario" type="submit" value="Actualizar" /></td>
		</tr>
	</table>
	<input type="hidden" name="id_usuario" value="<?= $perfil['id_usuario'] ?>" />
</form>